# CMake generated Testfile for 
# Source directory: /local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2
# Build directory: /local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GTK2Components.gtk "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gtk" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Components/gtk" "--build-generator" "Unix Makefiles" "--build-target" "gtk-all-libs" "--build-project" "gtk" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Components/gtk" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.glib "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/glib" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/glib" "--build-generator" "Unix Makefiles" "--build-project" "glib" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/glib" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gobject "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gobject" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gobject" "--build-generator" "Unix Makefiles" "--build-project" "gobject" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gobject" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gio "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gio" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gio" "--build-generator" "Unix Makefiles" "--build-project" "gio" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gio" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gmodule "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gmodule" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gmodule" "--build-generator" "Unix Makefiles" "--build-project" "gmodule" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gmodule" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gthread "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gthread" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gthread" "--build-generator" "Unix Makefiles" "--build-project" "gthread" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gthread" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.atk "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/atk" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/atk" "--build-generator" "Unix Makefiles" "--build-project" "atk" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/atk" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk_pixbuf "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gdk_pixbuf" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--build-generator" "Unix Makefiles" "--build-project" "gdk_pixbuf" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.cairo "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/cairo" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/cairo" "--build-generator" "Unix Makefiles" "--build-project" "cairo" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/cairo" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.pango "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/pango" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pango" "--build-generator" "Unix Makefiles" "--build-project" "pango" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pango" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.pangocairo "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/pangocairo" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--build-generator" "Unix Makefiles" "--build-project" "pangocairo" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoxft "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/pangoxft" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--build-generator" "Unix Makefiles" "--build-project" "pangoxft" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoft2 "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/pangoft2" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--build-generator" "Unix Makefiles" "--build-project" "pangoft2" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gdk" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gdk" "--build-generator" "Unix Makefiles" "--build-project" "gdk" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gdk" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
add_test(GTK2Targets.gtk "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "--build-and-test" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/gtk" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gtk" "--build-generator" "Unix Makefiles" "--build-project" "gtk" "--build-exe-dir" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/Tests/FindGTK2/GTK2Targets/gtk" "--force-new-ctest-process" "--test-command" "/local1/vaa3d_test/vaa3d_tools/hackathon/MK/NeuronStructNavigator/cmake-3.6.2/bin/ctest" "-V")
