#!/bin/bash
 
neuron_list=$1
work_dir=$2

if [ $# -eq 0 ]
then
  echo "Usage: flyem_skeletonize_cluster <neuron_list> <work directory>"
  exit 1
fi

./flyem_prepare_check $work_dir/cluster_map_body_tmp.sh

if [ $? -ne 0 ]
then
  echo "Not ready. Please wait for preparation to be complete or check if there is anything wrong."
fi

body_map_dir="$work_dir"/body_maps 
sorted_map_dir="$work_dir"/sorted_body_map
bin_dir=../cpp/debug/bin

testing=0
if [ $# -eq 4 ]
then
  testing=$4
fi

../cpp/debug/bin/generate_qsub_script --option skeletonize $neuron_list --cmd_path ~/Work/neutube/neurolabi/shell/flyem_skeletonize --work_dir $work_dir > $work_dir/cluster_skeletonize_tmp.sh

sh $work_dir/cluster_skeletonize_tmp.sh
