#!/bin/bash

if test $# -ne 1
then
    echo 'mkshell file'
else
    if [ -f $1 ]
    then
	echo "warning: file $1 exists"
    else
	echo '#!/bin/bash' > $1
	echo ' ' >> $1
	chmod a+x $1
	echo "$1 created"
    fi
    
    if test -d '/Applications/Aquamacs Emacs.app'
    then
	open -a '/Applications/Aquamacs Emacs.app' $1
    fi
fi