#!/usr/bin/perl

use File::Basename;

open (C1_INFO, '<', "../data/diadem_c1.txt");

@lines = <C1_INFO>;

my $index;
my @offset;
my $num_width;

foreach $line (@lines) {
  print $line;
  if ($line =~ m/([0-9]+).*\(X,Y,Z\):\s*\(([-0-9,]+)\)/) {
    $index = $1;
    print $index, "\n";

    @offset = split(/,/, $2);
    my $name = sprintf("%02d", $index);
    my $dir = "/Users/zhaot/Data/diadem/Neocortical Layer 6 Axons/Image Stacks/$name/";

    print $dir, "\n";
    opendir(DIR, $dir) || die "Error in opening dir $dir\n";
;
    my @files = grep(/tif/, readdir(DIR));
    if ($files[0] eq "01.tif") {
      $num_width = 2;
    } else {
      $num_width = 3;
    }
    closedir(DIR);

    open (XML, '>', "../data/diadem_c1_".$name.".xml");
    print XML "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    print XML "<trace>\n";
    print XML "<data>\n";
    print XML "<image type=\"bundle\">\n";
    print XML "<prefix>$dir</prefix>\n";
    print XML "<suffix>.tif</suffix>\n";
    print XML "<num_width>$num_width</num_width>\n";
    print XML "<first_num>1</first_num>\n";
    print XML "</image>\n";
    print XML "<offset><x>$offset[0]</x><y>$offset[1]</y><z>$offset[2]</z></offset>\n";
    print XML "<resolution><x>0.2941</x><y>0.2941</y><z>1</z></resolution>\n";
    print XML "</data>\n";
    print XML "<output>\n";
    print XML "<workdir>/Users/zhaot/Work/neurolabi/data</workdir>\n";
    print XML "<name>diadem_c1_".$name."</name>\n";
    print XML "</output>\n";
    print XML "</trace>\n";
    close (XML);
  }
}
