#!/bin/bash
 
cd ../c
plane_id=611
neuron_id=9187
while [ $plane_id -le 710 ]
do
  bin/testsmap --plane_id $plane_id --neuron_id $neuron_id -o "../data/flyem/neuron1/00$plane_id.tif"
  plane_id=`expr $plane_id + 1`
done
