#!/bin/bash
if [ $# -lt 2 ]
then
  echo 'Usage: flyem_skeletonize <data_dir> <work_dir>'
  exit 1
fi

data_dir=$1
work_dir=$2
body_map_dir="$work_dir"/body_maps 
sorted_map_dir="$work_dir"/sorted_body_map
if [ -z $SEG_CLUSTER_NAME ]
then
  bin_dir=$HOME/Work/buildem/bin
else
  bin_dir=$HOME/Work/buildem_cl/bin
fi

mkdir $body_map_dir
mkdir $body_map_dir/a
mkdir $sorted_map_dir

$bin_dir/sort_bodymap $data_dir -o $sorted_map_dir

if [ $? -ne 0 ]
then
  echo "skeletonization failed"
  exit 1
fi

#$bin_dir/map_body $data_dir --body_map $sorted_map_dir -o $body_map_dir --intv 4 4 0
$bin_dir/map_body $data_dir --body_map $sorted_map_dir -o $body_map_dir

if [ $? -ne 0 ]
then
  echo "skeletonization failed"
  exit 1
fi
