#!/bin/bash

input=$1
buildem_dir=$HOME/Work/buildem
PATH=$buildem_dir/bin:$PATH
PYTHONPATH=$buildem_dir/lib
tmpdir=/groups/flyem/home/zhaot/Work/neutube_ws/neurolabi/data/tmp

#Produce boundary predictions
if [ ! -f "$input/gala-pixel-output/STACKED_prediction.h5" ]
then
  gala-pixel --temp-dir $tmpdir --image-stack "$input/grayscale_maps/*.png" --ilp-file "/groups/flyem/data/medulla-FIB-Z1211-25/training/dots_ilastik06.ilp" "$input/gala-pixel-output"
fi

#Produce body graph
config_file="$input/gala-segmentation-config.json"
if [ ! -f "$config_file" ]
then
  echo "$config_file does not exist"
  exit 1
fi

gala-segmentation-pipeline --config-file "$config_file" $input/gala-segmentation
