#!/bin/bash
 
dlgclass=$1
dlgclass_upper=`toupper $dlgclass`
dlgclass_lower=`tolower $dlgclass`

echo '#include <QtGui>'
echo ' '
echo "#include \"$dlgclass_lower.h\""

echo "$dlgclass::$dlgclass(QWidget *parent) : QDialog(parent)"
echo '{'
if test -f "$dlgclass_lower.ui"
then
echo '  setupUi(this);'
fi
echo '}'
echo ' '
