#!/bin/bash

#if [ $# -gt 0 ]; then
#    for data in $*; do
#	echo $data
#	sh trace_all.sh $data
#    done
#else
#    while read data; do
#	echo $data
#	sh trace_all.sh $data -f
#    done
#fi

i=1
while [ $i -le 6 ]
do
    sh trace_all.sh diadem_c1_0$i -E xml -C
    i=`expr $i + 1`
done

#i=1
#while [ $i -le 152 ]
#do
#    if [ $i -lt 10 ]
#    then
#	sh trace_all.sh diadem_d1_00$i -E xml -C
#    elif [ $i -lt 100 ]
#    then
#	sh trace_all.sh diadem_d1_0$i -E xml -C
#    else
#	sh trace_all.sh diadem_d1_$i -E xml -C
#    fi
#    i=`expr $i + 1`
#done