#!/bin/bash

file=$2.c

echo "/**@file $file"
echo " * @author $1"
year=`date | sed 's_[ ][ ]*_-_g' | cut -d- -f6`
mon=`date | sed 's_[ ][ ]*_-_g' | cut -d- -f2`
day=`date | sed 's_[ ][ ]*_-_g' | cut -d- -f3`
if [ ${#day} -lt 2 ]
then
    day=0$day
fi
cur_date="$day-$mon-$year"
echo " * @date $cur_date" 
echo " */"

printf "\n"
echo '#include "tz_utilities.h"'
printf "\n"
echo 'int main(int argc, char *argv[])'
echo '{'
echo "  static char *Spec[] = {\"$3\", NULL};"
echo '  Process_Arguments(argc, argv, Spec, 1);'
printf "\n"
echo '  return 0;'
echo '}'
