// -*- c++ -*-
// Generated by gtkmmproc -- DO NOT MODIFY!
#ifndef _GDKMM_GL_WINDOW_H
#define _GDKMM_GL_WINDOW_H

#include <glibmm.h>

// -*- C++ -*-
/* gdkglextmm - C++ Wrapper for GdkGLExt
 * Copyright (C) 2002-2003  Naofumi Yasufuku
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.
 */

#include <gdkmm/gl/defs.h>

#include <gdkmm/drawable.h>
#include <gdkmm/window.h>

#include <gdkmm/gl/config.h>
#include <gdkmm/gl/drawable.h>


#ifndef DOXYGEN_SHOULD_SKIP_THIS
typedef struct _GdkGLWindow GdkGLWindow;
typedef struct _GdkGLWindowClass GdkGLWindowClass;
#endif /* DOXYGEN_SHOULD_SKIP_THIS */


namespace Gdk
{

namespace GL
{ class Window_Class; } // namespace GL

} // namespace Gdk
namespace Gdk
{
namespace GL
{

  /** OpenGL window which is located onscreen.
   *
   * @ingroup GLDrawables
   */


class Window : public Gdk::Drawable,
               public Gdk::GL::Drawable
{
  
#ifndef DOXYGEN_SHOULD_SKIP_THIS

public:
  typedef Window CppObjectType;
  typedef Window_Class CppClassType;
  typedef GdkGLWindow BaseObjectType;
  typedef GdkGLWindowClass BaseClassType;

private:  friend class Window_Class;
  static CppClassType window_class_;

private:
  // noncopyable
  Window(const Window&);
  Window& operator=(const Window&);

protected:
  explicit Window(const Glib::ConstructParams& construct_params);
  explicit Window(GdkGLWindow* castitem);

#endif /* DOXYGEN_SHOULD_SKIP_THIS */

public:
  virtual ~Window();

#ifndef DOXYGEN_SHOULD_SKIP_THIS
  static GType get_type()      G_GNUC_CONST;
  static GType get_base_type() G_GNUC_CONST;
#endif

  ///Provides access to the underlying C GObject.
  GdkGLWindow*       gobj()       { return reinterpret_cast<GdkGLWindow*>(gobject_); }

  ///Provides access to the underlying C GObject.
  const GdkGLWindow* gobj() const { return reinterpret_cast<GdkGLWindow*>(gobject_); }

  ///Provides access to the underlying C instance. The caller is responsible for unrefing it. Use when directly setting fields in structs.
  GdkGLWindow* gobj_copy();

private:


protected:
  Window(const Glib::RefPtr<const Config>& glconfig,
         const Glib::RefPtr<const Gdk::Window>& window,
         const int* attrib_list = 0);

public:
  
  static Glib::RefPtr<Window> create(const Glib::RefPtr<const Config>& glconfig, const Glib::RefPtr<const Gdk::Window>& window, const int* attrib_list =  0);


public:

  
  /** Returns the Gdk::Window associated with @a glwindow .
   * 
   * Notice that Gdk::GLWindow is not Gdk::Window, but another
   * Gdk::Drawable which have an associated Gdk::Window.
   * @return The Gdk::Window associated with @a glwindow .
   */
  Glib::RefPtr<Gdk::Window> get_window();

  
  /** Returns the Gdk::Window associated with @a glwindow .
   * 
   * Notice that Gdk::GLWindow is not Gdk::Window, but another
   * Gdk::Drawable which have an associated Gdk::Window.
   * @return The Gdk::Window associated with @a glwindow .
   */
  Glib::RefPtr<const Gdk::Window> get_window() const;


public:

public:
  //C++ methods used to invoke GTK+ virtual functions:

protected:
  //GTK+ Virtual Functions (override these to change behaviour):

  //Default Signal Handlers::


};

} // namespace GL
} // namespace Gdk


namespace Glib
{
  /** @relates Gdk::GL::Window
   * @param object The C instance
   * @param take_copy False if the result should take ownership of the C instance. True if it should take a new copy or ref.
   * @result A C++ instance that wraps this C instance.
   */
  Glib::RefPtr<Gdk::GL::Window> wrap(GdkGLWindow* object, bool take_copy = false);
}


#endif /* _GDKMM_GL_WINDOW_H */

