/* resample_swc_func.cpp
 * This is a plugin to resample neuron swc subject to a fixed step length.
 * 2012-03-02 : by Yinan Wan
 */

#include <v3d_interface.h>
#include "v3d_message.h"
#include "resample_swc_func.h"
#include "resampling.h"
#include <vector>
#include <iostream>
using namespace std;

const QString title = QObject::tr("Resample Neuron");

/*******************************************************
 * Split a string into string array
 * 1. args should be 0
 * 2. release args if not used any more
 *******************************************************/
int split(const char *paras, char ** &args)
{
    if(paras == 0) return 0;
    int argc = 0;
    int len = strlen(paras);
    int posb[2048];
    char * myparas = new char[len];
    strcpy(myparas, paras);
    for(int i = 0; i < len; i++)
    {
        if(i==0 && myparas[i] != ' ' && myparas[i] != '\t')
        {
            posb[argc++]=i;
        }
        else if((myparas[i-1] == ' ' || myparas[i-1] == '\t') &&
                (myparas[i] != ' ' && myparas[i] != '\t'))
        {
            posb[argc++] = i;
        }
    }

    args = new char*[argc];
    for(int i = 0; i < argc; i++)
    {
        args[i] = myparas + posb[i];
    }

    for(int i = 0; i < len; i++)
    {
        if(myparas[i]==' ' || myparas[i]=='\t')myparas[i]='\0';
    }
    return argc;
}

bool export_list2file(QList<NeuronSWC> & lN, QString fileSaveName, QString fileOpenName)
{
	QFile file(fileSaveName);
	if (!file.open(QIODevice::WriteOnly|QIODevice::Text))
		return false;
	QTextStream myfile(&file);
	myfile<<"# generated by Vaa3D Plugin resample_swc"<<endl;
	myfile<<"# source file(s): "<<fileOpenName<<endl;
	myfile<<"# id,type,x,y,z,r,pid"<<endl;
	for (V3DLONG i=0;i<lN.size();i++)
		myfile << lN.at(i).n <<" " << lN.at(i).type << " "<< lN.at(i).x <<" "<<lN.at(i).y << " "<< lN.at(i).z << " "<< lN.at(i).r << " " <<lN.at(i).pn << "\n";

	file.close();
	cout<<"swc file "<<fileSaveName.toStdString()<<" has been generated, size: "<<lN.size()<<endl;
	return true;
};

int resample_swc(V3DPluginCallback2 &callback, QWidget *parent)
{
	QString fileOpenName;
	fileOpenName = QFileDialog::getOpenFileName(0, QObject::tr("Open File"),
			"",
			QObject::tr("Supported file (*.swc *.eswc)"
				";;Neuron structure	(*.swc)"
				";;Extended neuron structure (*.eswc)"
				));
	if(fileOpenName.isEmpty()) 
		return 0;
	double step = 0;
	NeuronTree nt;
	if (fileOpenName.toUpper().endsWith(".SWC") || fileOpenName.toUpper().endsWith(".ESWC"))
	{
		bool ok;
		nt = readSWC_file(fileOpenName);
		step = QInputDialog::getDouble(parent, "Please specify the resampling step length","Step length:",1,0,2147483647,0.1,&ok);
		if (!ok)
			return 0;
	}
	
	NeuronTree result = resample(nt, step);
	
	QString fileDefaultName = fileOpenName+QString("_resampled.swc");
	//write new SWC to file
	QString fileSaveName = QFileDialog::getSaveFileName(0, QObject::tr("Save File"),
			fileDefaultName,
			QObject::tr("Supported file (*.swc)"
				";;Neuron structure	(*.swc)"
				));
	if (!export_list2file(result.listNeuron,fileSaveName,fileOpenName))
	{
		v3d_msg("fail to write the output swc file.");
		return 0;
	}


	return 1;
}

bool resample_swc(const V3DPluginArgList & input, V3DPluginArgList & output)
{
	cout<<"Welcome to resample_swc"<<endl;
	vector<char*>* inlist = (vector<char*>*)(input.at(0).p);
	vector<char*>* outlist = NULL;
	vector<char*>* paralist = NULL;

	if(input.size() != 2) 
	{
		printf("Please specify both input file and step length parameter.\n");
		return false;
	}
	paralist = (vector<char*>*)(input.at(1).p);
	if (paralist->size()!=1)
	{
		printf("Please specify only one parameter - the resampling step length.\n");
		return false;
	}
	double step = atof(paralist->at(0));

	QString fileOpenName = QString(inlist->at(0));
	QString fileSaveName;
	if (output.size()==0)
	{
		printf("No outputfile specified.\n");
		fileSaveName = fileOpenName + "_resampled.swc";
	}
	else if (output.size()==1)
		fileSaveName = QString(outlist->at(0));
	else
	{
		printf("You have specified more than 1 output file.\n");
		return false;
	}

	NeuronTree nt;
	if (fileOpenName.toUpper().endsWith(".SWC") || fileOpenName.toUpper().endsWith(".ESWC"))
		nt = readSWC_file(fileOpenName);
	
	NeuronTree result = resample(nt,step);
	if (!export_list2file(result.listNeuron, fileSaveName, fileOpenName))
	{
		printf("fail to write the output swc file.\n");
		return false;
	}

	return true;
}
