TEMPLATE      = lib
CONFIG       += qt plugin warn_off
#CONFIG       += x86_64
INCLUDEPATH  += ../../../v3d_main/basic_c_fun
HEADERS       = ada_threshold.h
SOURCES       = ada_threshold.cpp
SOURCES      += ../../../v3d_main/basic_c_fun/v3d_message.cpp
TARGET        = $$qtLibraryTarget(ada_threshold)
DESTDIR       = ../../v3d/plugins/image_thresholding/Simple_Adaptive_Thresholding
