# List of all structures supported by the configurable workflow engine
# (used by several tests)
# Update this list if support is added for new structures
SUPPORTED_STRUCTURE_NAMES = [
    "actb",
    "actn1",
    "atp2a2",
    "cetn2",
    "ctnnb1",
    "dsp",
    "fbl",
    "gja1",
    "h2b_interphase",
    "lamp1",
    "lmnb1_interphase",
    "lmnb1_mitotic",
    "myh10",
    "npm1",
    "nup153",
    "pxn",
    "rab5a",
    "sec61b",
    "slc25a17",
    "smc1a",
    "son",
    "st6gal1",
    "tjp1",
    "tomm20",
    "tuba1b",
]
