#!/bin/bash

if [ $# -lt 1 ]
then
  echo 'update <from>'
  exit 1
fi

from=$1

cp $from/CMakeLists.txt .
#cp $from/run_test .
cp $from/build_test .
#cp $from/RELEASE_NOTE .
cp -r $from/src .
#cp -r $from/test .
 
