# compile this plugin on mac with Qt4

# environment settings

QTPATH=/usr/local/Trolltech/Qt-4.7.1
ITKPATH=/usr/local
EIGENPATH=/usr/local


# compile

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o img.o img.cxx

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o neuronrecon_plugin.o neuronrecon_plugin.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o neuronrecon_func.o neuronrecon_func.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o neuronrecon.o neuronrecon.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o v3d_message.o ../../../../v3d_external/v3d_main/basic_c_fun/v3d_message.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o v_neuronswc.o ../../../../v3d_external/v3d_main/neuron_editing/v_neuronswc.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o basic_surf_objs.o ../../../../v3d_external/v3d_main/basic_c_fun/basic_surf_objs.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o basic_4dimage.o ../../../../v3d_external/v3d_main/basic_c_fun/basic_4dimage.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o imageio_mylib.o ../../../../v3d_external/v3d_main/basic_c_fun/imageio_mylib.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o v3d_nrrd.o ../../../../v3d_external/v3d_main/io/v3d_nrrd.cpp

${QTPATH}/bin/moc -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -D__APPLE__ -D__GNUC__ neuronrecon_plugin.h -o moc_neuronrecon_plugin.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o moc_neuronrecon_plugin.o moc_neuronrecon_plugin.cpp

${QTPATH}/bin/moc -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -D__APPLE__ -D__GNUC__ neuronrecon_func.h -o moc_neuronrecon_func.cpp

g++ -c -pipe -std=c++11 -stdlib=libc++ -Wno-c++11-narrowing -g -gdwarf-2 -w -fPIC -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I${QTPATH}/mkspecs/macx-g++ -I. -I${QTPATH}/lib/QtCore.framework/Versions/4/Headers -I${QTPATH}/include/QtCore -I${QTPATH}/lib/QtGui.framework/Versions/4/Headers -I${QTPATH}/include/QtGui -I${QTPATH}/include -I/usr/local/include -I${ITKPATH}/include/ITK-4.13 -I${EIGENPATH}/include/eigen3 -I../../../../v3d_external/v3d_main/basic_c_fun -I../../../../v3d_external/v3d_main/neuron_editing -I../../../../v3d_external/v3d_main/common_lib/include/boost/graph -I../../../../v3d_external/v3d_main/common_lib/include -I3rdparty -I. -F${QTPATH}/lib -o moc_neuronrecon_func.o moc_neuronrecon_func.cpp

g++ -headerpad_max_install_names -single_module -dynamiclib -o libneurontree_construct_debug.dylib img.o neuronrecon_plugin.o neuronrecon_func.o neuronrecon.o v3d_message.o v_neuronswc.o basic_surf_objs.o basic_4dimage.o imageio_mylib.o v3d_nrrd.o moc_neuronrecon_plugin.o moc_neuronrecon_func.o  -F${QTPATH}/lib -L${QTPATH}/lib -L../../../../v3d_external/v3d_main/common_lib/lib_mac64 -lv3dtiff -lteem -lbz2 -lz -L../../../../v3d_external/v3d_main/jba/c++ -lv3dnewmat /Users/yuy/work/alleninst/v3d_external/bin/plugins/neuron_tracing/ultratracer/libultratracer_debug.dylib -framework OpenCL -lc++ -litksys-4.13 -lITKVNLInstantiation-4.13 -litkvnl_algo-4.13 -litkvnl-4.13 -litkv3p_netlib-4.13 -litknetlib-4.13 -litkvcl-4.13 -lITKCommon-4.13 -lITKIOImageBase-4.13 -lITKIOTIFF-4.13 -lITKGPUAnisotropicSmoothing-4.13 -lITKGPUFiniteDifference-4.13 -lITKGPUCommon-4.13 -L../../../../v3d_external/v3d_main/common_lib/src_packages/mylib_tiff -lmylib -framework QtGui -L${QTPATH}/lib -F${QTPATH}/lib -framework QtCore 


# mv plugin to plugin folder
PluginDir=../../../bin/plugins/neuron_utilities/neurontree_construct
if [ -d "$PluginDir" ]; then
    echo "$PluginDir exists."
else
    mkdir $PluginDir
fi

mv libneurontree_construct_debug.dylib ${PluginDir}/

