function installSpineAnalysis
[fname, pname] = uigetfile({'*.*'}, 'Please specify the MatLab SpineAnalysis directory');
cd(pname);
[fname, binpname] = uigetfile({'*.*'}, 'Please specify the MatLab BIN directory');
[status,message,messageid] = copyfile('mex\3dmacommon.dll',binpname);
[status,message,messageid] = copyfile('mex\unzip.exe',binpname);
[status,message,messageid] = copyfile('mex\UNZDLL.DLL',binpname);
[status,message,messageid] = copyfile('mex\ZIPDLL.DLL',binpname);
addpath(pname, ...
        [pname 'guis\gui_building'],    ...
        [pname 'guis\gui_handling'],    ...
        [pname 'init_files'],           ...
        [pname 'io\file_io\initialization'],    ...
        [pname 'io\file_io\data'],              ...
        [pname 'mex'],                  ...
        [pname 'Objects'],              ...
        [pname 'utilities']);
 path2rc;