#!/bin/bash

version=debug
if test $# -eq 1
then
    if test $1 = release
    then
	version=release
    fi
fi

if test $version = debug
then
    exefile=neutube_d.app/Contents/MacOS/neutube_d
    if [ -f $exefile ]
    then
	rm $exefile
    fi
    make debug
else
    rm -r neutube.app
    make release
    macdeployqt neutube.app
 
    #exefile=itube.app/Contents/MacOS/itube
    #if [ -f $exefile ]
    #then
#	rm $exefile
#   fi
#    make release

#    install_name_tool -change /Library/Frameworks/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore itube.app/Contents/MacOs/itube
#    install_name_tool -change /Library/Frameworks/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui itube.app/Contents/MacOs/itube
#    install_name_tool -change /Library/Frameworks/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/QtCore itube.app/Contents/MacOs/itube
#    install_name_tool -change /Library/Frameworks/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/QtGui itube.app/Contents/MacOs/itube
#    install_name_tool -id @executable_path/../Frameworks/QtCore.framework/Versions/4/QtSvg itube.app/Contents/Frameworks/QtSvg.framework/Versions/4/QtSvg
#    install_name_tool -change /Library/Frameworks/lib/QtSvg.framework/Versions/4/QtSvg @executable_path/../Frameworks/QtSvg.framework/QtSvg itube.app/Contents/MacOs/itube

    #chmod a+w itube.app/Contents/Frameworks/libgsl.0.dylib
    #install_name_tool -change /usr/local/lib/libgsl.0.dylib @executable_path/../lib/libgsl.0.dylib itube.app/Contents/MacOs/itube
fi
	
 
