#!/bin/bash
BASEDIR=$(dirname $0)
cd $BASEDIR/c
cdir=`pwd`
make clean -f configure.makefile
allvar=$@
echo $allvar
make -f configure.makefile CONFIG_OPTION="--enable-64bit CFLAGS=-I$HOME/local/include LDFLAGS=-L$HOME/local/lib $allvar"

AFLAGS=-D_OPTIONAL_FLAGS

for var in "$@"
do
  if [ $var == "-nopb" ]; then
    AFLAGS=-DINTERFACE_PROGRESS_OFF
  fi
done

echo 'updating neurolabi ...'
cd $cdir

make clean
make lib AFLAGS="$AFLAGS"
for var in "$@"
do
  if [ $var == "--enable-shared" ]; then
    make dylib AFLAGS="$AFLAGS"
  fi
done

cd ..
