#ifndef NEURONSTRUCTNAVIGATOR_DEFINE_H
#define NEURONSTRUCTNAVIGATOR_DEFINE_H

#define Main_Version_Num 1
#define Sub_Version_Num 2
#define Patch_Num 9

//#define __SEGEND_CLUSTER_PRINTOUT__
//#define __SEGEND_CLUSTER_DEBUG__

//#define __MERGE2DCONNCOMPONENT_DEBUG__
//#define __MERGE2DCONNCOMPONENT_PRINTOUT__

//#define __SHELL_CONNECTED_COMPONENT_DEBUG__

//#define __RADIAL_DENDRITICTREE_GROWING_PRINTOUT__

#endif