#!/bin/bash

if [ -d tmp ]
then
  rm -r tmp
fi

mkdir tmp

if [ $# -eq 1 ]
then
  cmd=${HOME}/Work/neutube/neurolabi/cpp/psd_build/psd_compare
else
  cmd=${HOME}/Work/buildem/bin/psd_compare
fi

echo "Testing $cmd ..."

$cmd test/synapse_annotation1.json test/synapse_annotation2.json --config test/config.cfg --evaluate test/golden_match.csv --metric 0 --psdset1_agree tmp/psdset1_agree.json --psdset2_agree tmp/psdset2_agree.json --psdset1_verify tmp/psdset1_verify.json --psdset2_verify tmp/psdset2_verify.json --swc tmp/match.swc
 
