#ifndef FRAGTRACER_DEFINE_H
#define FRAGTRACER_DEFINE_H

#define MAINVERSION_NUM 0
#define SUBVERSION_NUM 9
#define PATCHVERSION_NUM 10

#define __IMAGE_VOLUME_PREPARATION_PRINTOUT__
//#define __IMAGE_VOLUME_PREPARATION_DEBUG__

#define __DENDRITE_BLOB_DEBUG__
#define __AXON_BLOB_DEBUG__

#define __DENDRITE_TREEFORMING_DEBUG__
//#define __DENDRITE_TREEFORMING_PERIPHERALSIGNAL_DEBUG__
#define __AXON_TREEFORMING_DEBUG__


#endif