#ifndef FRAGTRACER_DEFINE_H
#define FRAGTRACER_DEFINE_H

#define MAINVERSION_NUM 0
#define SUBVERSION_NUM 12
#define PATCHVERSION_NUM 2

#define __IMAGE_VOLUME_PREPARATION_PRINTOUT__
//#define __IMAGE_VOLUME_PREPARATION_DEBUG__

#define __DENDRITE_BLOB_DEBUG__
#define __AXON_BLOB_DEBUG__

#define __DENDRITE_TREEFORMING_DEBUG__
//#define __DENDRITE_TREEFORMING_PERIPHERALSIGNAL_DEBUG__
#define __AXON_TREEFORMING_DEBUG__

//#define __ERASER_DEBUG__

#define __CONTINUOUS_AXON_SEGEND_CLUSTER_DEBUG__
#endif