// This file has been generated by Py++.

#ifndef c_array_uint_4_hpp__pyplusplus_wrapper
#define c_array_uint_4_hpp__pyplusplus_wrapper

void register_c_array_uint_4_class();

#endif//c_array_uint_4_hpp__pyplusplus_wrapper
