// This file has been generated by Py++.

#ifndef c_array_int_3_hpp__pyplusplus_wrapper
#define c_array_int_3_hpp__pyplusplus_wrapper

void register_c_array_int_3_class();

#endif//c_array_int_3_hpp__pyplusplus_wrapper
