// This file has been generated by Py++.

#ifndef Image4DSimple_hpp__pyplusplus_wrapper
#define Image4DSimple_hpp__pyplusplus_wrapper

void register_Image4DSimple_class();

#endif//Image4DSimple_hpp__pyplusplus_wrapper
