// This file has been generated by Py++.

#ifndef ImageWindow_hpp__pyplusplus_wrapper
#define ImageWindow_hpp__pyplusplus_wrapper

void register_ImageWindow_class();

#endif//ImageWindow_hpp__pyplusplus_wrapper
