// This file has been generated by Py++.

#ifndef QVector_QPoint_hpp__pyplusplus_wrapper
#define QVector_QPoint_hpp__pyplusplus_wrapper

void register_QVector_QPoint_class();

#endif//QVector_QPoint_hpp__pyplusplus_wrapper
