// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrappable_v3d.h"
#include "RGB32i.pypp.hpp"

namespace bp = boost::python;

void register_RGB32i_class(){

    bp::class_< RGB32i >( "RGB32i" )    
        .def_readwrite( "b", &RGB32i::b )    
        .def_readwrite( "g", &RGB32i::g )    
        .def_readwrite( "r", &RGB32i::r )    
        .def_readwrite( "c", &RGB32i::c );

}
