// This file has been generated by Py++.

#ifndef TriviewControl_hpp__pyplusplus_wrapper
#define TriviewControl_hpp__pyplusplus_wrapper

void register_TriviewControl_class();

#endif//TriviewControl_hpp__pyplusplus_wrapper
