// This file has been generated by Py++.

#ifndef View3DControl_hpp__pyplusplus_wrapper
#define View3DControl_hpp__pyplusplus_wrapper

void register_View3DControl_class();

#endif//View3DControl_hpp__pyplusplus_wrapper
