%annotation analysis for the results generated by C code
%by Lei Qu @ 20101227

clc
clear all
close all


foldername='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/stanford_326/stanford_326_extracted_result';
% foldername='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/stanford_326/stanford_326_extracted_result_allothers_myproofreading_rmbadimg_nosph';
% foldername='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/stanford_326/stanford_326_extracted_result_allothers_myproofreading_rmbadimg_nosph_noflipsurppress';
% foldername='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/stanford_326/stanford_326_extracted_result_allothers_myproofreading_rmbadimg_nosph_noaniweight';
% foldername='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/stanford_326/stanford_326_extracted_result_allothers_myproofreading_rmbadimg_nosph_noflipsurppressnoaniweight';

% foldername='/groups/peng/penglab/Lei/atlasguided_stranno/paper/rot90_test/output';


%%
filename_apo_atlas='/groups/peng/home/qul/myhome/work/0.data/celegans_anno/atlas_related/atlas.apo';
apo_atlas=load_v3d_apo_file(filename_apo_atlas);

n=0;
arr_ind_muscle2atlas=[];

cellarr_muscelname={};
for i=1:length(apo_atlas)
    cellname=apo_atlas{i}.name;
    cellname=strtrim(cellname);
    cellname=upper(cellname);
    cellname(strfind(cellname,' '))='_';
    apo_atlas{i}.name=cellname;
    
%     if(~isempty(strfind(cellname,'BWM')) || strcmp(cellname,'SPH') || strcmp(cellname,'DEP'))
    if(~isempty(strfind(cellname,'BWM')) || strcmp(cellname,'DEP'))
        n=n+1;
        arr_ind_muscle2atlas(n)=i;
        cellarr_muscelname{n}=cellname;
    end
end


%%
curdir=dir(foldername);
n_file=0;
arr_cellnum_total=[];
arr_cellnum_correct=[];
arr_score_muscle=[];
arr_score_total=[];
arr_rotate90=[];
arr_wrongannonum=zeros(1,n);
arr_wrongannonum_norot90=zeros(1,n);
arr_rightratio_image=[];
arr2d_confusionmatrix=zeros(n+1,n+1);
n_muscle_right=[];
n_muscle_all=[];
for i=1:length(curdir)
    if(curdir(i).isdir || curdir(i).name(1)=='.')
%         fprintf('%s\n',curdir(i).name);
    else
        if(~isempty(strfind(curdir(i).name,'_analysis.txt')))
            n_file=n_file+1;
            fprintf('[%4d]: %s\n',n_file,curdir(i).name);

            %get analysis and info file full name
            filefullname_analysis=[foldername,'/',curdir(i).name];
            filefullname_info=[foldername,'/',curdir(i).name(1:end-length('_analysis.txt')),'_info.txt'];
            
            %read info file
            b_rotate90=0; b_flip=0;
            fid=fopen(filefullname_info,'r');
            while ~feof(fid)
                tline=fgetl(fid);
                
                if(~isempty(strfind(tline,'b_rotate90')))
%                     disp(tline);
                    ind=strfind(tline,'b_rotate90');
                    if(~isempty(ind))
                        tmp=tline(ind+11:end);
                        b_rotate90=str2double(tmp);
                        
                        arr_rotate90=[arr_rotate90;b_rotate90];
                    end
                end
                if(~isempty(strfind(tline,'b_flip')))
%                     disp(tline);
                    ind=strfind(tline,'b_flip');
                    if(~isempty(ind))
                        tmp=tline(ind+7:end);
                        b_flip=str2double(tmp);
                    end
                end
            end
            fclose(fid);
                        
            %read analysis file
            fid=fopen(filefullname_analysis,'r');
            while ~feof(fid)
                tline=fgetl(fid);
                
                %get total cell num and correct anno cell num
                ind=strfind(tline,'total=[');
                ind2=strfind(tline,'/');
                ind3=strfind(tline,']=');
                if(~isempty(ind) && ~isempty(ind2) && ~isempty(ind3))
                    tmp=tline(ind+7:(ind2-1)); 
                    cellnum_correct=str2double(tmp);
                    tmp=tline((ind2+1):(ind3-1)); 
                    cellnum_total=str2double(tmp);

                    arr_cellnum_total=[arr_cellnum_total;cellnum_total];
                    arr_cellnum_correct=[arr_cellnum_correct;cellnum_correct];
                end
                
                if(~isempty(strfind(tline,'rightanno_ratio_total')))
%                     disp(tline);
                    
                    %read correct anno ratio
                    ind=strfind(tline,']=');
                    if(~isempty(ind))
                        tmp=tline(ind+2:end); 
                        score_total=str2double(tmp)
                        arr_rightratio_image(n_file)=score_total;
                        
                        arr_score_total=[arr_score_total;score_total];
                    end
                                        
                    %read wrongly annotated cell name
                    if(score_total~=1)
                        tline=fgetl(fid);
                        disp(tline);
                        
                        ind_comma=strfind(tline,',');
                        if(~isempty(ind_comma))
                            ind_comma=[0,ind_comma];
                            for k=1:length(ind_comma)-1
                                commasection=tline(ind_comma(k)+1:ind_comma(k+1)-1);
                                ind_sep=strfind(commasection,'->');
                                cellname_wrong=commasection(1:ind_sep-1);
                                cellname_estimate=commasection(ind_sep+2:end);
                                %count the number of incorrect anno for each cell
                                ind_wronganno=strcmp(cellarr_muscelname,cellname_wrong);
                                arr_wrongannonum(ind_wronganno)=arr_wrongannonum(ind_wronganno)+1;
                                %count the number of incorrect anno for each cell (exclude the rot90 cases)
                                if(~arr_rotate90(end))
                                    ind_wronganno_norot90=strcmp(cellarr_muscelname,cellname_wrong);
                                    arr_wrongannonum_norot90(ind_wronganno_norot90)=arr_wrongannonum_norot90(ind_wronganno_norot90)+1;
                                end
                                %fill the confusion matrix
                                if(strcmp(cellname_estimate,'nan'))
                                    arr2d_confusionmatrix(ind_wronganno,end)=arr2d_confusionmatrix(ind_wronganno,end)+1;
                                else
                                    ind_estimate=strcmp(cellarr_muscelname,cellname_estimate);
                                    arr2d_confusionmatrix(ind_wronganno,ind_estimate)=arr2d_confusionmatrix(ind_wronganno,ind_estimate)+1;
                                end
                            end
                        end
                    end
                end
                if(~isempty(strfind(tline,'rightanno_ratio_muscle')))
                    disp(tline);
                    ind=strfind(tline,']=');
                    if(~isempty(ind))
                        tmp=tline(ind+2:end); 
                        score_muscle=str2double(tmp);
                        
                        arr_score_muscle=[arr_score_muscle;score_muscle];
                    end
                    ind_1=strfind(tline,'[');
                    ind_2=strfind(tline,'/');
                    ind_3=strfind(tline,']');
                    n_muscle_right(end+1)=str2double(tline(ind_1+1:ind_2-1));
                    n_muscle_all(end+1)=str2double(tline(ind_2+1:ind_3-1));
                end
                
            end
            fclose(fid);
            
            %output info
            if(score_muscle<0.9)
                fprintf('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n');
            end
            if(b_rotate90==1)
                fprintf('LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n');
            end
            if(b_flip==1)
                fprintf('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n');
            end

        end
    end
end
%fill the diagonal of confusion matrix
for i=1:n
    wrongannonum=sum(arr2d_confusionmatrix(i,:));
    arr2d_confusionmatrix(i,i)=n_file-wrongannonum;
end

% arr_rotate90(arr_score_total>0.95)=0;

%%
%compute the average score
avg_score_muslce=mean(arr_score_muscle)
avg_score_total=mean(arr_score_total)
arr_score_muscle_without90=mean(arr_score_muscle(arr_rotate90==0))
arr_score_total_without90=mean(arr_score_total(arr_rotate90==0))
cellnum_total=sum(arr_cellnum_total)
cellnum_total_without90=sum(arr_cellnum_total(arr_rotate90==0))
cellnum_correct_without90=sum(arr_cellnum_correct(arr_rotate90==0))
fprintf('correctannoratio_all=%f\n',sum(arr_cellnum_correct)/sum(arr_cellnum_total));
fprintf('correctannoratio_no90=%f\n',cellnum_correct_without90/cellnum_total_without90);

% sum(n_muscle_right(setdiff([1:n_file],46)))/sum(n_muscle_all(setdiff([1:n_file],46)))

%obtain the number of socre >= *
num_score95_muscle=nnz(arr_score_muscle>=0.95)
num_score95_total=nnz(arr_score_total>=0.95);

% %plot num of right/wrong anno of each cell (include rot90)
% fig=figure; hold on
% % fig=figure; grid on; hold on
% bar(1-arr_wrongannonum/n_file);
% % bar(arr_wrongannonum/n_file);
% set(gca,'XTick',1:length(arr_wrongannonum),'XTickLabel',cellarr_muscelname);
% xticklabel_rotate();
%plot num of right/wrong anno of each cell (exclude rot90)
fig1=figure; hold on
%(1) vertical bar
% bar(1-arr_wrongannonum_norot90/(n_file-length(find(arr_rotate90==1))));
% set(fig1,'color','white'); %set the background color to white
% xlabel('Cell ID');
% ylabel('Auto-recognition accuracy','Rotation',90);
% set(gca,'XTick',1:length(arr_wrongannonum_norot90),'XTickLabel',cellarr_muscelname);
% xticklabel_rotate();
%(2) horizon bar
barh(1-arr_wrongannonum_norot90/(n_file-length(find(arr_rotate90==1))));
% [xb,yb]=stairs(1-arr_wrongannonum_norot90/(n_file-length(find(arr_rotate90==1)))); plot(yb,xb);
set(fig1,'color','white'); %set the background color to white
ylabel('Cell ID');
xlabel('BWM Auto-recognition accuracy');
axis([0.93 1.02 0 length(arr_wrongannonum)+1]);
set(gca,'YTick',1:length(arr_wrongannonum),'YTickLabel',cellarr_muscelname);
annoratio=1-arr_wrongannonum_norot90/(n_file-length(find(arr_rotate90==1)));
for i=1:length(arr_wrongannonum)
    text(annoratio(i)+0.001,i,num2str(annoratio(i),'%.4f'));
end

%plot correct recognition ratio of each image
%(1) unsorted
fig2=figure; hold on
bar(arr_score_total);
set(fig2,'color','white'); %set the background color to white
axis([0 175 0 1]);
xlabel('Image ID');
ylabel('Auto-recognition accuracy','Rotation',90);
line(0:175,ones(1,176)*0.95,'LineStyle','--','Color','w');
text(60,1.04,'image number of accuracy >0.95: 165');
set(gca,'position',[0.04 0.1 0.95 0.85]);
% %(2) sorted
% arr_score_total_sort=sort(arr_score_total);
% fig2=figure; grid on;  hold on
% plot(arr_score_total_sort,'b.');
% % grid on;  hold on
% set(fig2,'color','white'); %set the background color to white
% axis([0 175 0 1]);
% xlabel('Image ID');
% ylabel('BWM Auto-recognition accuracy','Rotation',90);% bar(arr_score_total_sort);
% % stem(arr_score_total_sort);
% plot(arr_score_total_sort,'b.');
% line(0:175,ones(1,176)*0.95,'LineStyle','--');
% text(62,0.97,'image number of recognition accuracy >0.95: 165');
% %(3) vertical
% barh(arr_score_total);
% set(fig1,'color','white'); %set the background color to white
% ylabel('Image ID');
% xlabel('BWM Auto-recognition accuracy');

% %build histogram
% n_bin=7;
% arr_bin=zeros(n_bin,1);
% arr_bin(1)=length(intersect(find(arr_score_total>=0),find(arr_score_total<0.2)));
% arr_bin(2)=length(intersect(find(arr_score_total>=0.2),find(arr_score_total<0.4)));
% arr_bin(3)=length(intersect(find(arr_score_total>=0.4),find(arr_score_total<0.6)));
% arr_bin(4)=length(intersect(find(arr_score_total>=0.6),find(arr_score_total<0.8)));
% arr_bin(5)=length(intersect(find(arr_score_total>=0.8),find(arr_score_total<0.9)));
% arr_bin(6)=length(intersect(find(arr_score_total>=0.9),find(arr_score_total<0.95)));
% arr_bin(7)=length(intersect(find(arr_score_total>=0.95),find(arr_score_total<=1)));
% arr_bin
% figure; bar(arr_bin);
