#ifndef __NS_IMAGE_PIXELS_BLUR_H__
#define __NS_IMAGE_PIXELS_BLUR_H__

#include <math/nsconv.h>
#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_BLUR_PIXEL_TYPE,
	NS_PIXEL_PROC_BLUR_SRC_PIXELS,
	NS_PIXEL_PROC_BLUR_WIDTH,
	NS_PIXEL_PROC_BLUR_HEIGHT,
	NS_PIXEL_PROC_BLUR_LENGTH,
	NS_PIXEL_PROC_BLUR_ROW_ALIGN,
	NS_PIXEL_PROC_BLUR_DEST_PIXELS,
	NS_PIXEL_PROC_BLUR_REGION,
	NS_PIXEL_PROC_BLUR_PROGRESS,

	NS_PIXEL_PROC_BLUR_NUM_PARAMS
	};


NS_IMPEXP NsProc* ns_pixel_proc_blur( void );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_BLUR_H__ */
