#ifndef __NS_IMAGE_PIXELS_BRIGHTNESS_CONTRAST_H__
#define __NS_IMAGE_PIXELS_BRIGHTNESS_CONTRAST_H__

#include <std/nsmath.h>
#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_PIXEL_TYPE,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_PIXELS,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_WIDTH,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_HEIGHT,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_LENGTH,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_ROW_ALIGN,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_BRIGHTNESS,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_CONTRAST,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_REGION,
	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_PROGRESS,

	NS_PIXEL_PROC_BRIGHTNESS_CONTRAST_NUM_PARAMS
	};


#define NS_BRIGHTNESS_MIN  -.5
#define NS_BRIGHTNESS_MAX  .5
#define NS_CONTRAST_MIN    -1.0
#define NS_CONTRAST_MAX    1.0

NS_IMPEXP NsProc* ns_pixel_proc_brightness_contrast( void );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_BRIGHTNESS_CONTRAST_H__ */
