#ifndef __NS_IMAGE_PIXELS_NOISE_H__
#define __NS_IMAGE_PIXELS_NOISE_H__

#include <std/nsmath.h>
#include <math/nsrandom.h>
#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_NOISE_PIXEL_TYPE,
	NS_PIXEL_PROC_NOISE_PIXELS,
	NS_PIXEL_PROC_NOISE_WIDTH,
	NS_PIXEL_PROC_NOISE_HEIGHT,
	NS_PIXEL_PROC_NOISE_LENGTH,
	NS_PIXEL_PROC_NOISE_ROW_ALIGN,
	NS_PIXEL_PROC_NOISE_LEVEL,
	NS_PIXEL_PROC_NOISE_ITERATIONS,
	NS_PIXEL_PROC_NOISE_AVERAGE_INTENSITY,
	NS_PIXEL_PROC_NOISE_SIGNAL_TO_NOISE_RATIO,
	NS_PIXEL_PROC_NOISE_REGION,
	NS_PIXEL_PROC_NOISE_PROGRESS,

	NS_PIXEL_PROC_NOISE_NUM_PARAMS
	};


NS_IMPEXP NsProc* ns_pixel_proc_noise( void );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_NOISE_H__ */
