#ifndef __NS_IMAGE_PIXELS_FLIP_H__
#define __NS_IMAGE_PIXELS_FLIP_H__

#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_FLIP_PIXEL_TYPE,
	NS_PIXEL_PROC_FLIP_PIXELS,
	NS_PIXEL_PROC_FLIP_WIDTH,
	NS_PIXEL_PROC_FLIP_HEIGHT,
	NS_PIXEL_PROC_FLIP_LENGTH,
	NS_PIXEL_PROC_FLIP_ROW_ALIGN,
	NS_PIXEL_PROC_FLIP_TYPE,
	NS_PIXEL_PROC_FLIP_PROGRESS,

	NS_PIXEL_PROC_FLIP_NUM_PARAMS
	};


typedef enum
	{
	NS_PIXEL_PROC_FLIP_VERTICAL,
	NS_PIXEL_PROC_FLIP_HORIZONTAL,
	NS_PIXEL_PROC_FLIP_OPTICAL_AXIS,

	_NS_PIXEL_PROC_FLIP_NUM_TYPES
	}
	NsPixelProcFlipType;

#define NS_PIXEL_PROC_FLIP_NUM_TYPES  ( ( nsenum )_NS_PIXEL_PROC_FLIP_NUM_TYPES )


NS_IMPEXP NsProc* ns_pixel_proc_flip( void );

NS_IMPEXP const nschar* ns_pixel_proc_flip_type_to_string( NsPixelProcFlipType type );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_FLIP_H__ */
