#ifndef __NS_IMAGE_PIXELS_RESIZE_H__
#define __NS_IMAGE_PIXELS_RESIZE_H__

#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_RESIZE_PIXEL_TYPE,
	NS_PIXEL_PROC_RESIZE_SRC_PIXELS,
	NS_PIXEL_PROC_RESIZE_SRC_WIDTH,
	NS_PIXEL_PROC_RESIZE_SRC_HEIGHT,
	NS_PIXEL_PROC_RESIZE_SRC_LENGTH,
	NS_PIXEL_PROC_RESIZE_SRC_ROW_ALIGN,
	NS_PIXEL_PROC_RESIZE_INTERP_TYPE,
	NS_PIXEL_PROC_RESIZE_DEST_PIXELS,
	NS_PIXEL_PROC_RESIZE_DEST_WIDTH,
	NS_PIXEL_PROC_RESIZE_DEST_HEIGHT,
	NS_PIXEL_PROC_RESIZE_DEST_LENGTH,
	NS_PIXEL_PROC_RESIZE_DEST_ROW_ALIGN,
	NS_PIXEL_PROC_RESIZE_PROGRESS,

	NS_PIXEL_PROC_RESIZE_NUM_PARAMS
	};


typedef enum
	{
	NS_PIXEL_PROC_RESIZE_NEAREST_NEIGHBOR,

	_NS_PIXEL_PROC_RESIZE_NUM_TYPES
	}
	NsPixelProcResizeType;

#define NS_PIXEL_PROC_RESIZE_NUM_TYPES  ( ( nsenum )_NS_PIXEL_PROC_RESIZE_NUM_TYPES )


NS_IMPEXP const nschar* ns_pixel_proc_resize_type_to_string( NsPixelProcResizeType type );

NS_IMPEXP NsProc* ns_pixel_proc_resize( void );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_RESIZE_H__ */
