#ifndef __NS_IMAGE_PIXELS_GAMMA_CORRECT_H__
#define __NS_IMAGE_PIXELS_GAMMA_CORRECT_H__

#include <std/nsmath.h>
#include <image/nspixels.h>

NS_DECLS_BEGIN

enum
	{
	NS_PIXEL_PROC_GAMMA_CORRECT_PIXEL_TYPE,
	NS_PIXEL_PROC_GAMMA_CORRECT_PIXELS,
	NS_PIXEL_PROC_GAMMA_CORRECT_WIDTH,
	NS_PIXEL_PROC_GAMMA_CORRECT_HEIGHT,
	NS_PIXEL_PROC_GAMMA_CORRECT_LENGTH,
	NS_PIXEL_PROC_GAMMA_CORRECT_ROW_ALIGN,
	NS_PIXEL_PROC_GAMMA_CORRECT_GAMMA,
	NS_PIXEL_PROC_GAMMA_CORRECT_REGION,
	NS_PIXEL_PROC_GAMMA_CORRECT_PROGRESS,

	NS_PIXEL_PROC_GAMMA_CORRECT_NUM_PARAMS
	};

NS_IMPEXP NsProc* ns_pixel_proc_gamma_correct( void );

NS_DECLS_END

#endif/* __NS_IMAGE_PIXELS_GAMMA_CORRECT_H__ */
