set(ITK_DIR /Users/pengh/work/vaa3d_tools/hackathon/ITK-V3D-Plugins/itkbuild)
#set(V3D_BINARY_DIR /Users/ping/yp/vaa3d/bin/)
set (V3D_BINARY_DIR /Users/pengh/work/v3d_external/bin)
set(V3D_BASIC_C_FUN_SOURCE_DIR /Users/pengh/work/v3d_external/v3d_main/basic_c_fun/)
#set(CMAKE_BUILD_TYPE Release)
