set(ITK_DIR /Users/ping/yp/ITK/build_new)
#set(V3D_BINARY_DIR /Users/ping/yp/vaa3d/bin/)
set (V3D_BINARY_DIR /Users/ping/yp/vaa3d/)
set(V3D_BASIC_C_FUN_SOURCE_DIR /Users/ping/yp/vaa3d/v3d_main/basic_c_fun/)
#set(CMAKE_BUILD_TYPE Release)
