#!/bin/bash

DIR="$( cd -P "$( dirname "$0" )" && pwd )"
cd $DIR

if [ -d ./__tmp_cmake_tmp__ ]
then 
	rm -rf __tmp_cmake_tmp__
fi

mkdir __tmp_cmake_tmp__
cd __tmp_cmake_tmp__

rm -f ../c/CMakeCache.txt

unamestr=`uname`

if [[ "$unamestr" == MINGW32* ]]; then
cmake ../c -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"
else
cmake ../c -DCMAKE_BUILD_TYPE=Debug
fi

make clean
make
make clean

if [[ "$unamestr" == MINGW32* ]]; then
cmake ../c -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"
else
cmake ../c -DCMAKE_BUILD_TYPE=Release
fi

make
make install

cd ..
rm -rf __tmp_cmake_tmp__
