#!/bin/bash

if [ $# -lt 1 ]
then
  echo 'install_library <destination> [<lib_name>]'
  exit 1
fi

echo "Installing neurolabi..."

BASEDIR=$(dirname $0)
if [ $BASEDIR = "." ]
then
  BASEDIR=$PWD
fi

cd $BASEDIR/c

INSTALL_DIR=$1
INSTALL_LIB_DIR=$1/lib
INSTALL_INCLUDE_DIR=$1/include/neurolabi

echo "  Lib: $INSTALL_LIB_DIR"
echo "  Include: $INSTALL_INCLUDE_DIR"

if [ ! -d $INSTALL_LIB_DIR ]; then mkdir -p $INSTALL_LIB_DIR; fi
if [ ! -d $INSTALL_INCLUDE_DIR ]; then mkdir -p $INSTALL_INCLUDE_DIR; fi

LIB_DIR=lib

ORIGINAL_LIB_NAME=libneurolabi
INSTALL_LIB_NAME=libneurolabi
if [ $# -eq 2 ]
then
  INSTALL_LIB_NAME=$2
fi

echo "  Installing $INSTALL_LIB_NAME..."

if [ -f $LIB_DIR/$ORIGINAL_LIB_NAME.dylib ]
then
  echo "    cp $LIB_DIR/$ORIGINAL_LIB_NAME.dylib $INSTALL_LIB_DIR/$INSTALL_LIB_NAME.dylib"
  cp $LIB_DIR/$ORIGINAL_LIB_NAME.dylib $INSTALL_LIB_DIR/$INSTALL_LIB_NAME.dylib
  install_name_tool -id "$INSTALL_LIB_DIR/$INSTALL_LIB_NAME.dylib" $INSTALL_LIB_DIR/$INSTALL_LIB_NAME.dylib
fi

if [ -f $LIB_DIR/$ORIGINAL_LIB_NAME.so ]
then
  echo "    cp $LIB_DIR/$ORIGINAL_LIB_NAME.so $INSTALL_LIB_DIR/$INSTALL_LIB_NAME.so"
  cp $LIB_DIR/$ORIGINAL_LIB_NAME.so $INSTALL_LIB_DIR/$INSTALL_LIB_NAME.so
fi

MYERS_DIR=../lib/genelib/src

echo "  Installing header files..."
cp *.h $INSTALL_INCLUDE_DIR        
chmod a+w $INSTALL_INCLUDE_DIR/*.h
cp include/*.h $INSTALL_INCLUDE_DIR
cp $MYERS_DIR/*.h $INSTALL_INCLUDE_DIR
if [ ! -d $INSTALL_INCLUDE_DIR/neulib_cpp ]
then
  mkdir $INSTALL_INCLUDE_DIR/neulib_cpp
fi
cp -r $BASEDIR/gui/* $INSTALL_INCLUDE_DIR/neulib_cpp


