#!/bin/bash
 
i=$2
neuron_id=$1
#datadir="../data/flyem/dalhousie"
datadir="/media/Iomega HDD/data/dalhousie"
outdir="/media/wd/data/dalhousie-20120717/neuron$neuron_id"
mkdir "$outdir"
while [ $i -le $3 ]
  do
  echo $i
  if [ $i -lt 1000 ] 
  then
  infile="$datadir/body_maps/sp_map.00$i.tif"
  outfile="$outdir/sp_map.00$i.tif"
  if [ ! -f "$outfile" ]
  then
  if [ -f "$infile" ]
  then
  ../cpp/debug/bin/extract_neuron "$infile" -o "$outfile" --body_id $neuron_id
  fi
  fi
  else
  infile="$datadir/body_maps/sp_map.0$i.tif"
  outfile="$outdir/sp_map.0$i.tif"
  if [ ! -f "$outfile" ]
  then
  if [ -f "$infile" ]
  then
  ../cpp/debug/bin/extract_neuron "$infile" -o "$outfile" --body_id $neuron_id
  fi
  fi
  fi
  i=`expr $i + 1`
done
