#!/bin/bash

classname=$1
pluginclass="$classname"Plugin
filename=`tolower $pluginclass`

if test $2 = 'h'
then
    filepath=$filename.h
    mkqtplugin_header $classname $pluginclass > $filepath
elif test $2 = 'cpp'
then
    filepath=$filename.cpp
    mkqtplugin_source $classname $pluginclass $filename > $filepath
elif test $2 = 'pro'
then
    filepath=$filename.pro
    mkqtplugin_pro $classname $pluginclass > $filepath
else
    echo 'Wrong file type'
fi