#!/bin/bash
 
if test $# -ne 1
then
    echo 'mkqtdlg dialog_class'
else
    dlgclass=$1
    dlgclass_lower=`tolower $dlgclass`
    mkqtdlg_header $dlgclass > $dlgclass_lower.h
    mkqtdlg_source $dlgclass > $dlgclass_lower.cpp
fi