#!/bin/bash

if [ $# -ne 2 ]
then
    echo 'sw "keyword" "file"'
else
    for keyword in $1
    do
	echo "$keyword"
	for file in $2
	do
	    result=`grep -E -h -n -w $keyword $file`
	    #echo $result

	    if [ $? -eq 0 ]
	    then
	        new_result=`echo "$result" | cut -d: -f1`
		printf "    $file: "
		for x in $new_result
		do
		    printf " $x"
		done
		printf '\n'
	    fi
	done
    done
fi
