#!/bin/bash
 
i=161
datadir="/media/wd/data/dalhousie-20120717"
#neuron_id=285743
neuron_id=$1
mkdir "$datadir/neuron$neuron_id"
while [ $i -le 1460 ]
  do
  echo $i
  if [ $i -lt 1000 ] 
  then
  ../c/bin/imds "$datadir/superpixel_maps/sp_map.00$i.png" -o "../data/flyem/dalhousie/ds/sp_map.00$i.tif" --intv 4 4 0
  #../cpp/debug/bin/test "$datadir/ds/sp_map.00$i.tif" -o "$datadir/body_maps/sp_map.00$i.tif" --body_map "$datadir/pixel_body/bodymap_$i" --plane_id $i
  #../cpp/debug/bin/extract_neuron "$datadir/body_maps/sp_map.00$i.tif" -o "$datadir/neuron$neuron_id/sp_map.00$i.tif" --body_id $neuron_id
  else
  ../c/bin/imds "$datadir/superpixel_maps/sp_map.0$i.png" -o "../data/flyem/dalhousie/ds/sp_map.0$i.tif" --intv 4 4 0
  #../cpp/debug/bin/test "$datadir/ds/sp_map.0$i.tif" -o "$datadir/body_maps/sp_map.0$i.tif" --body_map "$datadir/pixel_body/bodymap_$i" --plane_id $i
  #../cpp/debug/bin/extract_neuron "$datadir/body_maps/sp_map.0$i.tif" -o "$datadir/neuron$neuron_id/sp_map.0$i.tif" --body_id $neuron_id
  fi
  i=`expr $i + 1`
done
