#!/bin/bash

classname=$1
classname_lower=`tolower $classname`
pluginclass=$2
pluginclass_lower=`tolower $pluginclass`
filename=$3

echo "#include \"$filename.h\""
echo ' '
echo "$pluginclass::$pluginclass(QObject *parent) : QObject(parent)"
echo '{'
echo ' '
echo '}'
echo ' '
echo "QString $pluginclass::name() const"
echo '{'
echo "  return \"$classname\";"
echo '}'
echo ' '
echo "QString $pluginclass::includeFile() const"
echo '{'
echo "  return \"$classname_lower.h\";"
echo '}'
echo ' '
echo "QString $pluginclass::group() const"
echo '{'
echo '  //return tr("My Widgets");'
echo '}'
echo ' '
echo "QIcon $pluginclass::icon() const"
echo '{'
echo "  //return QIcon(\":/images/$classname_lower.png\");"
echo '}'
echo ' '
echo "QString $pluginclass::toopTip() const"
echo '{'
echo "  return tr(\"A $classname widget\");"
echo '}'
echo ' '
echo "QString $pluginclass::whatsThis() const"
echo '{'
echo "  //return tr(\"What's this?\");"
echo '}'
echo ' '
echo "bool $pluginclass::isContainer() const"
echo "{"
echo "  return false;"
echo "}"
echo ' '
echo "QWidget *$pluginclass::createWidget(QWidget *parent)"
echo '{'
echo "  return new $classname(parent);"
echo '}'
echo ' '
echo "W_EXPORT_PLUGIN2($pluginclass_lower, $pluginclass)"
