#!/bin/bash
 
classname=$1
pluginclass=$2
classname_lower=`tolower $classname`
pluginclass_lower=`tolower $pluginclass`

echo 'TEMPLATE = lib'
echo 'CONFIG += designer plugin release'
echo "HEADERS = ../$classname_lower/$classname_lower.h $pluginclass_lower.h"
echo "SOURCES = ../$classname_lower/$classname_lower.cpp $pluginclass_lower.cpp"
echo "RESOURCES = $pluginclass_lower.qrc"
echo 'DESTDIR = $$[QT_INSTALL_PLUGINS]/designer'