#!/usr/bin/perl
 
my $s;
my @scores;
my @calctime;

$s = 0.1;
my @avgscores;
my @params;
my @tcosts;
my $k = 0;

while ($s < 0.5) {

  $start = time();
  $scores[0] = diadem_score("benchmark/diadem/diadem_e1", "e1", '31 430 0', $s);
  #$scores[0] = 0;
  $end = time();
  $calctime[0] = $end - $start;

  $start = time();
  $scores[1] = diadem_score("benchmark/diadem/diadem_e2", "e2", '1 391 25', $s);
  #$scores[1] = 0;
  $end = time();
  $calctime[1] = $end - $start;

  $start = time();
  $scores[2] = diadem_score("benchmark/diadem/diadem_e3", "e3", '94 179 38', $s);
  #$scores[2] = 0;
  $end = time();
  $calctime[2] = $end - $start;

  $start = time();
  $scores[3] = diadem_score("benchmark/diadem/diadem_e4", "e4",
      '128.2 504.37 0.303', $s);
  $end = time();
  $calctime[3] = $end - $start;

  $start = time();
  $scores[4] = diadem_score("benchmark/diadem/diadem_e5", "e5",
      '185.7 264.02 33', $s);
  $end = time();
  $calctime[4] = $end - $start;

  $start = time();
  $scores[5] = diadem_score("benchmark/diadem/diadem_e6", "e6",
      '15.074 412.01 10', $s);
  $end = time();
  $calctime[5] = $end - $start;

  $average_score = mean(@scores);

  push @params, $s;
  push @avgscores, $average_score;
  push @tcosts, mean(@calctime);
  print $k, "\n";
  $k++;

  $s += 0.01;
}

print "@params", "\n";
print "@avgscores", "\n";
print "@tcosts", "\n";
print "\n";

sub diadem_score {
    my ($data, $id, $root, $s) = @_;
    system "cd ../c; sh trace_all.sh $data -T 2 -r no_recon -s $s";

    $args = "-o struct.txt -minlen 0 -b -z 1.0 -res ../data/diadem_e3.res -screen -sp -sl -rz -dist 20";

    system "cd ../c; bin/reconstruct_neuron -D../data/$data -I../data/$data.tif -root $root $args";

    system "java -jar DiademMetric.jar -G /Users/zhaot/Data/diadem/$id"."_fix.swc -T /Users/zhaot/Work/neurolabi/data/$data/graph_d.swc -D 5 -m true > ../data/$data/rvtest.out";

    open RESULT, '<', "../data/$data/rvtest.out";

    while (<RESULT>) {
	if (m/[sS]core[: ]+([0-9.]+)/) {
	    $score = $1;
	    break;
	}
    }
    return $score;
}

sub mean {
    my @args = @_;
    my $sum = 0;
    foreach $arg (@args) {
	$sum += $arg;
    }
    return $sum/@args;
}
