#!/bin/bash

bodyid_array=(277709 386464 280303 2341 278848 545716 455131 545944 5189 476680 588435 460193 515936 586983 546035 475117 547009 547221 455135)
index=1
for bodyid in ${bodyid_array[@]}
do
  prefix=T4_${index}
  /Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
  index=$((index+1))
done

#bodyid=277709
#prefix=T4_1
#/Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
# 
#bodyid=386464
#prefix=T4_2
#/Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
# 
#bodyid=476680
#prefix=T4_10
#/Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
# 
#bodyid=475117
#prefix=T4_16
#/Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
# 
#bodyid=547009
#prefix=T4_17
#/Users/zhaot/Work/neutube/neurolabi/cpp/debug/bin/project_synapse /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/annotations-synapse.json /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/Mi1*.json  --swc /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.swc --body_id $bodyid -o /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/len15/adjusted/"$prefix"_$bodyid.marker --synapse psd_only --config /Users/zhaot/Work/neutube/neurolabi/data/flyem/skeletonization/session2/config.cfg --neuron_type /Users/zhaot/Work/neutube/neurolabi/data/flyem/TEM/neuron_type.txt
# 
